config/routes.rb
Rails.application.routes.draw do
  match 'products/index', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_products, dependent: :delete_all
  has_many :products, through: :category_products

  after_commit :reindex_products

  def reindex_products
    products.each(&:reindex)
  end
end

app/models/category_product.rb
class CategoryProduct < ApplicationRecord
  belongs_to :category
  belongs_to :product

  after_commit :reindex_products

  private

  def reindex_products
    prod_index = Product.find(product_id)
    prod_index.reindex
  end
end

app/models/product.rb
class Product < ApplicationRecord
  searchkick index_name: "#{Rails.env.to_s}-products",
             suggest: [:title, :categories],
             highlight: [:title, :description]
             # conversions: 'conversions'

  has_many :category_products, dependent: :delete_all
  has_many :categories, through: :category_products

  def search_data
    { title: title,
      description: description,
      active: active,
      is_deleted: is_deleted,
      created_at: created_at,
      categories: categories.map(&:name),
      category_ids: category_ids }
    # conversions: searches.group(:query).uniq.count(:user_id)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @term = params[:search]
    @products = products.presence || products(partial: true)
    @categories = group_categories
    @similar = similar
  end

  private

  def products(partial: false)
    attr = partial ? options.merge(operator: 'or') : options
    Product.search(@term.presence || '*', attr)
  end

  def options
    { includes: [:categories],
      suggest: true,
      misspellings: {distance: 2},
      page: 1,
      per_page: 10,
      where: {active: true, is_deleted: false},
      order: {created_at: :desc},
      aggs: [:categories],
      fields: ['title^10', 'categories^5', 'description'],
      highlight: {tag: "<strong>"} }
  end

  def group_categories
    return [] unless @products.present?

    @products.aggs['categories']['buckets'].map { | category |
      { name: category['key'], count: category['doc_count'] }
    }
  end

  def similar
    return unless params[:product_id].present?

    prod = Product.find(params[:product_id])

    prod.similar(fields: ['categories'],
                 includes: [:categories],
                 misspellings: {distance: 2},
                 page: params[:page].presence || 1,
                 per_page: 10,
                 where: {active: true, is_deleted: false},
                 order: {created_at: :desc})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchkickElastic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products#index</h1>
<%= form_tag products_index_path, :method => :post do %>
  <p>
    <%= text_field_tag :search, @term %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<% if @products.present? %>
  <h1>Productos</h1>

  <% if @products.suggestions.present? %>
    <p>quiso decir: <b><%= @products.suggestions.join(',')  %></b></p>
  <% end %>

  <% unless @products.last_page? %>
    <%= link_to 'Next', products_index_path(page:  @products.next_page, search: @term) %>
  <% end %>

  <table>
  <thead>
    <th>Name</th>
    <th>Precio</th>
    <th>Descripcion</th>
    <th>Categoria</th>
    <th></th>
  </thead>
  <tbody>
     <% @products.each do |pro| %>
        <tr>
          <td><%= (pro.search_highlights[:title] || pro.title).html_safe %></td>
          <td><%= pro.price %></td>
          <td><%= (pro.search_highlights[:description] || pro.description).html_safe %></td>
          <td><%= pro.categories.map(&:name) %></td>
          <td><%= link_to 'similares', products_index_path(product_id: pro.id) %></td>
        </tr>
     <% end %>
  </tbody>
  </table>
  <br>
  <table border="2">
  <thead>
    <tr>
      <td>Pagina actual</td>
      <td>siguiente</td>
      <td>total paginas</td>
      <td>es la primera</td>
      <td>es la ultima</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @products.current_page %></td>
      <td><%= @products.next_page %></td>
      <td><%= @products.total_pages %></td>
      <td><%= @products.first_page? %></td>
      <td><%= @products.last_page? %></td>
      <td></td>
    </tr>
  </tbody>
  </table>
  <br>

  <% if @categories.present? %>
    <table>
      <thead>
      <% @categories.each do |category| %>
        <tr>
          <td><%= "#{category[:name]}(#{category[:count]})" %></td>
        </tr>
      <% end %>
      </thead>
    </table>
  <% end %>

  <% if @similar.present? %>
    <h1>Similares</h1>
    <table>
      <thead>
      <th>Name</th>
      <th>Precio</th>
      <th>Descripcion</th>
      <th>Categorias</th>
      </thead>
      <tbody>
      <% @similar.each do |pro| %>
        <tr>
          <td><%= pro.title %></td>
          <td><%= pro.price %></td>
          <td><%= pro.description %></td>
          <td><%= pro.categories.map(&:name) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% end %>

<% end %>